
name: Node.js CD

on:
  push:
    branches: [ "i18n" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    - name: Install dependencies
      run: npm i
      working-directory: ./pca-ui/src/www

    - name: Run unit tests
      run: npm t
      working-directory: ./pca-ui/src/www